apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: nallaramasuryaprakash2002/bookstore:try
        ports:
        - containerPort: 8081
        readinessProbe:  # Checks if the container is ready to serve requests
          httpGet:
            path: /health  # Adjust the path based on your application's health endpoint
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:  # Checks if the container is alive
          httpGet:
            path: /health  # Adjust the path based on your application's health endpoint
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 15
