apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore  # Matches the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80        # External port exposed by the service
      targetPort: 8081 # Port your app is running on
      nodePort: 31000  # Custom NodePort (optional)
  type: NodePort      # Exposing service using NodePort (no external load balancer)
