apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use "nlb" for Network Load Balancer, or omit for Classic LB
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"  # Optional, based on your app's health check path
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "HTTP"  # Protocol your app listens to
spec:
  selector:
    app: bookstore
  ports:
    - protocol: TCP
      port: 80      # Expose port 80 externally
      targetPort: 8081  # Forward traffic to port 8081 inside the container
  type: LoadBalancer
