apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
  labels:
    app: bookstore
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Using AWS Network Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: bookstore
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-secondary-service
  labels:
    app: bookstore-secondary
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Using AWS Network Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: bookstore-secondary
  ports:
  - protocol: TCP
    port: 8081 # Changed port to avoid conflict with Jenkins
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Using AWS Network Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080 # Jenkins port, unchanged
    targetPort: 8080
